name: Build AnchorMacro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build --no-daemon

      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: AnchorMacro-JAR
          path: build/libs/*.jar
