name: Build AnchorMacro Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Grant execute permission to gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4️⃣ Build the mod using Gradle wrapper
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 5️⃣ Upload the build artifact (JAR)
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AnchorMacro-mod
          path: build/libs/*.jar
