name: Build AnchorMacro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Fabric Mod
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Build the mod using Gradle wrapper
      - name: Build mod
        run: ./gradlew build --no-daemon

      # 5. Upload the built JAR
      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: AnchorMacro-JAR
          path: build/libs/*.jar
