name: Build AnchorMacro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Show java/gradle info (debug)
        run: |
          java -version
          uname -a
          ls -la
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show gradle wrapper info (debug)
        run: ./gradlew --version

      - name: Build (no daemon)
        run: ./gradlew build --no-daemon

      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: AnchorMacro-JAR
          path: build/libs/*.jar
