name: Build AnchorMacro Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Make Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4️⃣ Build the mod
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 5️⃣ Upload built JAR
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnchorMacro-mod
          path: build/libs/*.jar
